import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import type { SSHConfig } from '@/shared/types';
import { Eye, EyeOff, Lock, KeyRound } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

interface SshEditDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  initialData: SSHConfig | null;
  onSave: (data: SSHConfig) => void;
}

export function SshEditDialog({ open, onOpenChange, initialData, onSave }: SshEditDialogProps) {
  const { t } = useTranslation();
  const [formData, setFormData] = useState<SSHConfig>({
    id: '',
    name: '',
    host: '',
    port: 22,
    username: 'root',
  });
  const [authType, setAuthType] = useState<'password' | 'key'>('password');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (open) {
      if (initialData) {
        setFormData({ ...initialData });
        setAuthType(initialData.privateKey ? 'key' : 'password');
      } else {
        // New SSH Connection
        setFormData({
          id: '', // Will be generated by store
          name: '',
          host: '',
          port: 22,
          username: 'root',
        });
        setAuthType('password');
      }
      setError('');
    }
  }, [open, initialData]);

  const handleSave = () => {
    const trimmedName = formData.name?.trim() || formData.host; // Fallback to host if name empty
    if (!trimmedName) {
      setError(t('ssh.errorNameHostEmpty'));
      return;
    }
    const trimmedHost = formData.host.trim();
    if (!trimmedHost) {
        setError(t('ssh.errorHostEmpty'));
        return;
    }

    onSave({ 
        ...formData, 
        name: trimmedName, 
        host: trimmedHost,
        // Clear the other auth method
        password: authType === 'password' ? formData.password : undefined,
        privateKey: authType === 'key' ? formData.privateKey : undefined
    });
    onOpenChange(false);
  };

  const updateField = (patch: Partial<SSHConfig>) => {
    setFormData((prev) => ({ ...prev, ...patch }));
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{initialData ? t('ssh.editTitle') : t('ssh.addTitle')}</DialogTitle>
          <DialogDescription>
            {t('ssh.editDesc')}
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="name" className="text-right">
              {t('ssh.name')}
            </Label>
            <Input
              id="name"
              value={formData.name || ''}
              onChange={(e) => updateField({ name: e.target.value })}
              className="col-span-3"
              placeholder="My Remote Server"
            />
          </div>

          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="host" className="text-right">
              {t('ssh.host')}
            </Label>
            <Input
              id="host"
              value={formData.host}
              onChange={(e) => updateField({ host: e.target.value })}
              className="col-span-3"
              placeholder="192.168.1.100"
            />
          </div>

          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="port" className="text-right">
              {t('ssh.port')}
            </Label>
            <Input
              id="port"
              type="number"
              value={formData.port}
              onChange={(e) => updateField({ port: parseInt(e.target.value) || 22 })}
              className="col-span-3"
              placeholder="22"
            />
          </div>

          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="username" className="text-right">
              {t('ssh.username')}
            </Label>
            <Input
              id="username"
              value={formData.username}
              onChange={(e) => updateField({ username: e.target.value })}
              className="col-span-3"
              placeholder="root"
            />
          </div>

          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="token" className="text-right">
              FRPS Token
            </Label>
            <Input
              id="token"
              type="password"
              value={formData.token || ''}
              onChange={(e) => updateField({ token: e.target.value })}
              className="col-span-3"
              placeholder="FRPS Auth Token (Optional)"
            />
          </div>

          <div className="grid grid-cols-4 items-start gap-4">
             <Label className="text-right pt-2">{t('ssh.authMethod')}</Label>
             <div className="col-span-3 space-y-3">
                 <div className="flex bg-muted rounded-md p-1 gap-1 w-fit">
                    <Button 
                        type="button"
                        variant={authType === 'password' ? 'default' : 'ghost'} 
                        size="sm" 
                        className="h-7 px-3 text-xs shadow-none"
                        onClick={() => setAuthType('password')}
                    >
                        <Lock className="h-3 w-3 mr-1.5" /> {t('ssh.password')}
                    </Button>
                    <Button 
                        type="button"
                        variant={authType === 'key' ? 'default' : 'ghost'} 
                        size="sm" 
                        className="h-7 px-3 text-xs shadow-none"
                        onClick={() => setAuthType('key')}
                    >
                        <KeyRound className="h-3 w-3 mr-1.5" /> {t('ssh.privateKey')}
                    </Button>
                 </div>

                 {authType === 'password' ? (
                    <div className="relative">
                        <Input 
                            type={showPassword ? "text" : "password"} 
                            placeholder="••••••••" 
                            value={formData.password || ''}
                            onChange={(e) => updateField({ password: e.target.value })}
                        />
                        <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                            onClick={() => setShowPassword(!showPassword)}
                        >
                            {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                        </Button>
                    </div>
                 ) : (
                    <Textarea 
                        placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"
                        className="font-mono text-xs min-h-[100px] resize-none"
                        value={formData.privateKey || ''}
                        onChange={(e) => updateField({ privateKey: e.target.value })}
                    />
                 )}
             </div>
          </div>
        </div>

        {error && <div className="text-sm text-red-500 mb-2 text-right">{error}</div>}

        <DialogFooter>
          <Button type="submit" onClick={handleSave}>{t('ssh.saveConnection')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
